### ISSUE TITLE
Data collection - DISCOVERY - Decide what categories we want to identify, and what corresponding links we want to attach to them?

### ISSUE THREAD

**Issue by Ammar-tcd** [Ammar-tcd/SwEng-Group-14-SemanticProductLink#7]

**Comment by DanPreda90** [comment]
Completed - We have created a list of categories we want to identify

**Comment by Ammar-tcd** [comment]
Categories to be recognized are available in the link below.
https://github.com/Ammar-tcd/SwEng-Group-14-SemanticProductLink/blob/Dan-Backend/Training_Data/Labels.txt

**Comment by Ammar-tcd** [comment]
Links to those categories is available in a doc shared below.
https://docs.google.com/document/d/1rbgN1Iji0P654MIikhiXWjkNwbXhdpEh2g7x3cQsw2I/edit?usp=sharing
